# Generated by Django 2.2.4 on 2019-09-10 06:33

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=100)),
                ('article_content', markdownx.models.MarkdownxField()),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.CharField(default='Masterclass Admin', max_length=100)),
            ],
        ),
    ]
